/*
 * 参数定义
 */

// 设备分类结构-作为搜索条件和列展示
var equipmentStructure = {
	"控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"名称" : "EQU_NAME",
		"功能描述" : "ELEC",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"制造厂" : "EQU_MANUFACTURER",
		"投用时间" : "EQU_COMMISSION_DATE",
		"备注" : "CAPCITY"
	},
	"DCS系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"SIS/FGS系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"导热油控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"除盐水控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"硫磺过滤机控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"火炬控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"变频供水控制系统" : {
		"设备状态":"EQU_MEMO_TWO",
		"系统序号" : "EQU_WORK_TEMP",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"数量" : "MEASURE_PRIN",
		"单位" : "FLUX",
		"输入点类型" : "PROCE_LINK_TYPE",
		"输入点数量" : "FLA_SIZE",
		"备注" : "CAPCITY"
	},
	"检测回路" : {
		"设备状态":"EQU_MEMO_TWO",
		"位号" : "EQU_POSITION_NUM",
		"功能描述" : "ELEC",
		"仪表类型" : "MEDUIM_TYPE",
		"规格型号" : "EQU_MODEL",
		"测量范围" : "VAVLE_TYPE",
		"单位" : "FLUX",
		"厂家" : "EQU_MANUFACTURER",
		"备注" : "CAPCITY"
	},
	"控制回路" : {
		"设备状态":"EQU_MEMO_TWO",
		"控制功能描述" : "ACTUAL_MODEL",
		"控制变量-位号" : "EQU_POSITION_NUM",
		"控制变量-测量范围" : "ACTUAL",
		"控制变量-控制范围" : "ELEC_MODEL",
		"控制变量-单位" : "ELEC",
		"执行设备-位号" : "MEASURE_PRIN",
		"执行设备-功能描述" : "PIPE_OUTER",
		"执行设备-控制规律" : "FLUX",
		"备注" : "CAPCITY"
	},
	"控制系统安全联锁回路" : {
		"设备状态":"EQU_MEMO_TWO",
		"联锁条件-位号" : "DEEP_LENGTH",
		"联锁条件-联锁条件描述" : "VAVLE_TYPE",
		"联锁条件-测量范围" : "ACTUAL",
		"联锁条件-联锁范围" : "ACTUAL_MODEL",
		"联锁条件-单位" : "ELEC_MODEL",
		"联锁执行设备-位号" : "PIPE_OUTER",
		"联锁执行设备-功能描述" : "POSITIONER",
		"联锁执行设备-联锁动作" : "PROCE_LINK_TYPE",
		"备注" : "CAPCITY"
	},
	"气动（电动）切断阀" : {
		"设备状态":"EQU_MEMO_TWO",
		"位号" : "EQU_POSITION_NUM",
		"功能描述" : "MEDUIM_TYPE",
		"阀体-规格型号" : "DEEP_LENGTH",
		"阀体-工程直径" : "VAVLE_TYPE",
		"阀体-材质" : "MEASURE_PRIN",
		"执行器-型号" : "PIPE_OUTER",
		"执行器-电气接口尺寸" : "POSITIONER",
		"执行器-气源接口尺寸" : "PROCE_LINK_TYPE",
		"执行器-供气（供电）电源" : "ELECTRIC_PRES",
		"执行器-厂家" : "EQU_MANUFACTURER",
		"投用时间" : "EQU_COMMISSION_DATE",
		"备注" : "CAPCITY"
	},
	"气动（电动）调节阀" : {
		"设备状态":"EQU_MEMO_TWO",
		"位号" : "EQU_POSITION_NUM",
		"所在装置" : "WEL_NAME",
		"功能描述" : "ACTUAL",
		"阀体-规格型号" : "DEEP_LENGTH",
		"阀体-工程直径" : "VAVLE_TYPE",
		"阀体-材质" : "MEASURE_PRIN",
		"执行器-型号" : "PIPE_OUTER",
		"执行器-电气接口尺寸" : "POSITIONER",
		"执行器-气源接口尺寸" : "PROCE_LINK_TYPE",
		"执行器-供气（供电）电源" : "ELECTRIC_PRES",
		"执行器-流量特性" : "ELEC",
		"执行器-额定CV" : "CV",
		"执行器-厂家" : "EQU_MANUFACTURER",
		"投用时间" : "EQU_COMMISSION_DATE",
		"备注" : "CAPCITY"
	},
	"电工器具" : {
		"设备状态":"EQU_MEMO_TWO",
		"单位" : "WEL_NAME",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"出厂/自编号" : "EQU_WORK_TEMP",
		"生产厂家" : "EQU_MANUFACTURER",
		"放置地点" : "DEEP_LENGTH",
		"使用状态" : "PROCE_LINK_TYPE",
		"检定周期" : "ACTUAL",
		"上次检定日期" : "EQU_COMMISSION_DATE",
		"1次计划检定日期" : "FREQUENCY",
		"2次计划检定日期" : "BRAND",
		"检测单位" : "FLUX",
		"检定结果" : "GAS_SOURCE",
		"保管人" : "ELECTRIC_PRES",
		"备注" : "CAPCITY"
	},
	"静设备" : {
		"设备状态":"EQU_MEMO_TWO",
		"设备名称" : "EQU_NAME",
		"设备位号" : "EQU_POSITION_NUM",
		"生产装置" : "WEL_NAME",
		"规格型号" : "EQU_MODEL",
		"设备类型" : "SPINDLE_SPEED",
		"资产原值" : "MEDUIM_TYPE",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂日期" : "EQU_PRODUC_DATE",
		"出厂编号" : "EQU_WORK_TEMP",
		"投用日期" : "EQU_COMMISSION_DATE",
		"主体材质" : "DEEP_LENGTH",
		"重量Kg" : "VAVLE_TYPE",
		"壳程-介质" : "ACTUAL_MODEL",
		"壳程-设计压力MPa" : "ACTUAL",
		"壳程-设计温度℃" : "ELEC_MODEL",
		"管程-介质" : "ELEC",
		"管程-设计压力MPa" : "MEASURE_PRIN",
		"管程-设计温度℃" : "PIPE_OUTER",
		"换热面积m2" : "FLUX",
		"安全阀-数量" : "PIPE_THICK",
		"安全阀-规格型号" : "CV",
		"腐蚀余量" : "POSITIONER",
		"过滤精度" : "GAS_SOURCE",
		"容器类别" : "FLA_SIZE",
		"注册编号" : "PROCE_LINK_TYPE",
		"使用证编号" : "POWER_RATE",
		"检验报告编号" : "ELECTRIC_PRES",
		"安全状况等级" : "ELECTRIC_TENSION",
		"检验情况-上次检验日期" : "FREQUENCY",
		"检验情况-下次检验日期" : "BRAND",
		"备注" : "CAPCITY"
	},
	"动设备" : {
		"设备状态":"EQU_MEMO_TWO",
		"设备名称" : "EQU_NAME",
		"设备位号" : "EQU_POSITION_NUM",
		"生产装置" : "WEL_NAME",
		"规格型号" : "EQU_MODEL",
		"设备类型" : "SPINDLE_SPEED",
		"资产原值" : "MEDUIM_TYPE",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂日期" : "EQU_PRODUC_DATE",
		"出厂编号" : "EQU_WORK_TEMP",
		"主体材质" : "DEEP_LENGTH",
		"重量KG" : "VAVLE_TYPE",
		"介质" : "ACTUAL_MODEL",
		"流量（m3/h）" : "AFTER_BEARING1",
		"扬程（m）" : "GREASE_INTERV",
		"效率（%）" : "GREASE_QUAN",
		"进/出口 压力（MPa）" : "INSULATION_RATE",
		"密封方式" : "PROTECTION_RATE",
		"冷却方式" : "PHASE_NUMBER",
		"联轴器结构形式" : "CONNECTION_GROUP",
		"电机功率（kw）" : "HEIGHT_ELECTRIC_PRES	",
		"轴转速（rpm）" : "WEIGHT",
		"备注" : "SNATCH_ELECTRIC_PRES"
	},
	"管道" : {
		"设备状态":"EQU_MEMO_TWO",
		"所在装置名称" : "WEL_NAME",
		"管道名称" : "EQU_NAME",
		"管道编号" : "EQU_WORK_TEMP",
		"设计单位" : "EQU_MANUFACTURER",
		"安装单位" : "PEAK_TENSION",
		"安装年月" : "EQU_DESIGN_TEMP",
		"投用年月" : "CORROSION_FATIGUE",
		"规格-公称直径mm" : "DESIGN_TUBE_TEMP",
		"规格-公称壁厚mm" : "DESIGN_TUBE_PRES",
		"规格-管道长度mm" : "OPTION_SHELL_PRESS",
		"设计/操作条件-压力Mpa" : "OPTION_SHELL_IN_TEMP",
		"设计/操作条件-温度℃" : "OPTION_SHELL_OUT_TEMP",
		"设计/操作条件-介质" : "OPTION_SHELL_MEDUIM",
		"防护保温涂层方式" : "OPTION_TUBE_IN_TEMP",
		"管道材质" : "OPTION_TUBE_OUT_TEMP",
		"焊口数量" : "OPTION_TUBE_MEDUIM",
		"管道级别" : "SHELL_MATERIAL",
		"安全状况等级" : "TUBE_MATERIAL",
		"检验情况-上次检验日期" : "EQU_LASTPERIODIC_DATE",
		"检验情况-计划检验日期" : "DISPLACEMENT",
		"报告编号" : "SPINDLE_MEDUIM",
		"备注" : "PUMP_MEDUIM"
	},
	"安全阀" : {
		"设备状态":"EQU_MEMO_TWO",
		"单位" : "EQU_MANUFACTURER",
		"安装地点" : "EQU_INSTALL_POSITION",
		"安全阀型号、规格" : "EQU_MODEL",
		"整定压力（MPa）" : "WIND_PRESSURE",
		"实际工作压力（MPa）" : "WEL_NAME",
		"制造单位" : "ENGINE_NUMBER",
		"压力级别范围（Mpa）" : "LICENSE_NUMBER",
		"产品编号" : "EQU_WORK_TEMP",
		"出厂日期" : "EQU_PRODUC_DATE",
		"启用日期" : "EQU_COMMISSION_DATE",
		"上次校验日期" : "EQU_LASTPERIODIC_DATE",
		"计划校验日期" : "DISPLACEMENT",
		"工作介质" : "ENERGY_CONSUMPTION_CAT",
		"工作温度（℃）" : "SERIAL_NUM",
		"安装高度（米）" : "CHECK_CYCLE",
		"备注" : "MEASURE_ACC"
	},
	"锅炉" : {
		"设备状态":"EQU_MEMO_TWO",
		"位号" : "EQU_POSITION_NUM",
		"名称" : "EQU_NAME",
		"出厂编号" : "EQU_WORK_TEMP",
		"技术规格" : "EQU_MODEL",
		"制造单位" : "EQU_MANUFACTURER",
		"登记编号" : "DEEP_LENGTH",
		"注册代码" : "ORDER_NUM",
		"投用年月" : "VAVLE_TYPE",
		"额定出力" : "ACTION_MODLE",
		"技术特性-设计压力壳/管(Mpa)" : "HAVE_NOT",
		"技术特性-设计温度壳/管(℃)" : "ACTUAL_MODEL",
		"技术特性-操作压力壳/管(Mpa)" : "ACTUAL",
		"技术特性-操作温度壳/管(℃)" : "ELEC_MODEL",
		"技术特性-物料名称" : "ELEC",
		"检验报告编号" : "MEASURE_PRIN",
		"检验情况-上次检验日期" : "EQU_LASTPERIODIC_DATE",
		"检验情况-计划检验日期" : "DISPLACEMENT",
		"资产价值" : "PIPE_OUTER",
		"备注" : "FLUX"

	},
	"厂内车辆" : {
		"设备状态":"EQU_MEMO_TWO",
		"名称" : "EQU_NAME",
		"出厂编号" : "EQU_WORK_TEMP",
		"技术规格" : "EQU_MODEL",
		"厂内编号" : "DEEP_LENGTH",
		"厂内牌照编号" : "POWER_RATE",
		"空车  重量（kg）" : "ELECTRIC_PRES",
		"载重量（kg）" : "ELECTRIC_TENSION",
		"最高时速（km/h）" : "FREQUENCY",
		"燃料种类" : "BRAND",
		"设备注册代码" : "CAPCITY",
		"制造单位" : "EQU_MANUFACTURER",
		"投用年月" : "SPEED_RAT",
		"上次检验日期" : "EQU_LASTPERIODIC_DATE",
		"计划检验日期	" : "DISPLACEMENT",
		"定检报告" : "GREASE_QUAN",
		"安装位置" : "EQU_INSTALL_POSITION",
		"资产价值" : "PIPE_OUTER",
		"备注" : "PROTECTION_RATE"
	},
	"气体报警仪表" : {
		"设备状态":"EQU_MEMO_TWO",
		"站点名称" : "HAVE_NOT",
		"类别" : "ACTUAL_MODEL",
		"投运日期" : "EQU_PRODUC_DATE",
		"气体报警器-名称" : "EQU_NAME",
		"气体报警器-型号规格" : "EQU_MODEL",
		"气体报警器-器具编号" : "EQU_WORK_TEMP",
		"气体报警器-准确度等级" : "FREQUENCY",
		"气体报警器-测量范围" : "BRAND",
		"气体报警器-安装位置" : "EQU_INSTALL_POSITION",
		"气体报警器-生产厂家" : "EQU_MANUFACTURER",
		"固定式报警仪信号-使用状态" : "DEEP_LENGTH",
		"固定式报警仪信号-系统型号规格" : "ORDER_NUM",
		"固定式报警仪信号-生产厂家" : "VAVLE_TYPE",
		"固定式报警仪信号-报警、连锁功能是否正常" : "OPTION_TUBE_IN_TEMP",
		"检定周期" : "CHECK_CYCLE",
		"上次检定日期" : "EQU_LASTPERIODIC_DATE",
		"计划检定日期1" : "OPTION_TUBE_OUT_TEMP",
		"计划检定日期2" : "OPTION_TUBE_MEDUIM",
		"检定方式" : "GREASE_QUAN"

	},
	"标准孔板" : {
		"设备状态":"EQU_MEMO_TWO",
		"外径" : "GREASE_INTERV",
		"内径-出厂值" : "GREASE_QUAN",
		"内径-实测值" : "INSULATION_RATE",
		"厚度(mm)" : "PROTECTION_RATE",
		"材质" : "EXPLOSION_RATE",
		"制造厂家" : "EQU_MANUFACTURER",
		"检定单位" : "FREQUENCY",
		"检定日期" : "BRAND",
		"投运日期" : "EQU_COMMISSION_DATE",
		"场站" : "CONNECTION_GROUP",
		"井号或用户" : "SNATCH_ELECTRIC_PRES",
		"状态" : "SNATCH_ELECTRIC_TENSION",
		"存放地点" : "MATERIAL",
		"新/报废" : "EQU_DESIGN_TEMP",
		"入库日期/停用日期" : "EQU_PRODUC_DATE",
		"备注" : "CAPCITY"
	},
	"计量标准器具" : {
		"设备状态":"EQU_MEMO_TWO",
		"单位" : "WEL_NAME",
		"名称" : "EQU_NAME",
		"规格型号" : "EQU_MODEL",
		"准确度等级" : "DEEP_LENGTH",
		"出厂编号" : "EQU_WORK_TEMP",
		"出厂日期" : "EQU_PRODUC_DATE",
		"生产厂家" : "EQU_MANUFACTURER",
		"投用日期" : "EQU_COMMISSION_DATE",
		"放置地点" : "POSITIONER",
		"使用状态" : "GAS_SOURCE",
		"检定周期" : "FLA_SIZE",
		"上次检定日期" : "FREQUENCY",
		"计划检定日期" : "BRAND",
		"检定单位" : "MEASURE_PRIN",
		"检定结果" : "PIPE_THICK",
		"保管人" : "SHELL_MATERIAL",
		"备注" : "CAPCITY"
	},
	"流量计量器具" : {
		"设备状态":"EQU_MEMO_TWO",
		"站名" : "CATEGORY",
		"地理位置" : "EXPLOSION_RATE",
		"计量对象" : "DEVICE_TYPE",
		"计量性质" : "HEIGHT_ELECTRIC_TENSION",
		"资产归属" : "PHASE_NUMBER",
		"投运日期" : "CONNECTION_GROUP",
		"流量计量-装置名称" : "WEL_NAME",
		"流量计量-型号规格" : "WEIGHT",
		"流量计量-编号" : "MATERIAL",
		"流量计量-准确度等级" : "CORROSION_FATIGUE",
		"流量计量-PN" : "EQU_DESIGN_TEMP",
		"流量计量-DN" : "DESIGN_PRESSURE_RANGE",
		"流量计量-D20" : "SURFACE_HEAT_TRANSFER",
		"流量计量-生产厂家" : "EQU_MANUFACTURER",
		"流量计量-使用状态" : "DESIGN_SHELL_PRES",
		"计量系统-名称" : "DESIGN_SHELL_TEMP",
		"计量系统-型号" : "DESIGN_TUBE_TEMP",
		"计量系统-生产厂家" : "ENERGY_CONSUMPTION_CAT",
		"检定周期" : "OPTION_SHELL_PRESS",
		"上次检定日期" : "FREQUENCY",
		"计划检定日期" : "BRAND",
		"检定方式" : "OPTION_SHELL_IN_TEMP",
		"检定单位" : "OPTION_SHELL_OUT_TEMP",
		"检定结果" : "OPTION_SHELL_MEDUIM",
		"备注" : "CAPCITY"

	},
	"生产过程监控计量器具" : {
		"设备状态":"EQU_MEMO_TWO",
		"站点名称" : "WEL_NAME",
		"类别" : "DEVICE_TYPE",
		"投运日期" : "EQU_COMMISSION_DATE",
		"名称" : "EQU_NAME",
		"型号规格" : "EQU_MODEL",
		"器具编号" : "EQU_WORK_TEMP",
		"准确度等级" : "LICENSE_NUMBER",
		"测量范围" : "WIND_PRESSURE",
		"安装位置" : "TUBE_MATERIAL",
		"生产厂家" : "OPTION_TUBE_OUT_TEMP",
		"使用状态" : "OPTION_TUBE_IN_TEMP",
		"检定周期" : "OPTION_SHELL_MEDUIM",
		"上次检定日期" : "FREQUENCY",
		"计划检定日期" : "BRAND",
		"检定方式" : "PHASE_NUMBER",
		"检定单位" : "HEIGHT_ELECTRIC_TENSION",
		"检定结果" : "COUNT",
		"备注" : "CAPCITY"
	}

};