/*
 * 参数定义
 */

//设备分类结构-作为搜索条件和列展示
var equipmentStructure = {
	"全部设备" : { 
		"装置列名" : "WEL_NAME",
		"装置单元" : "WEL_UNIT",
		"设备类别" : "EQU_MEMO_ONE",
		"设备位号" : "EQU_POSITION_NUM",
		"设备名称" : "EQU_NAME",
	},
	"仪表设备" : {
		"仪表设备" : "SECONDCLASS_EQUIPMENT"
	},
	"机械设备" : {
		"机械设备" : "SECONDCLASS_EQUIPMENT"
	},
	"电气设备" : {
		"电气设备" : "SECONDCLASS_EQUIPMENT"
	},
	"分析化验设备" : {
		"分析化验设备" : "SECONDCLASS_EQUIPMENT"
	},
	"压力表" : {
		"器具类别" : "MANAGE_TYPE",
		"规格型号" : "EQU_MODEL",
		"测量范围" : "MEARING_RANGE",
		"准确等级" : "MEASURE_ACC",
		"安装地点" : "EQU_INSTALL_POSITION",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"检定周期" : "CHECK_CYCLE",
		"检定日期" : "CHECK_TIME",
		"下次检定" : "NEXT_CHECK_TIME",
		"备注信息" : "REMARK1"
	},
	"压力差压变送器" : {				
		"器具类别" : "MANAGE_TYPE",
		"规格型号" : "EQU_MODEL",
		"测量介质" : "MEDUIM_TYPE",
		"测量范围" : "MEARING_RANGE",
		"精度" : "MEASURE_ACC",
		"安装地点" : "EQU_INSTALL_POSITION",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"检定周期" : "CHECK_CYCLE",
		"检定日期" : "CHECK_TIME",
		"有效期" : "NEXT_CHECK_TIME",
		"备注信息" : "REMARK1"				
	},
	"温度计" : {
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"插深" : "DEEP_LENGTH",
		"接口尺寸" : "INTER_SIZE",
		"测量介质" : "MEDUIM_TYPE",
		"测量范围" : "MEARING_RANGE",
		"精度" : "MEASURE_ACC",				
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"检定周期" : "CHECK_CYCLE",
		"检定日期" : "CHECK_TIME",
		"有效期" : "NEXT_CHECK_TIME",
		"备注信息" : "REMARK1"				
	},
	"温度变送器" : {
		"分度号" : "ORDER_NUM",
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"插深" : "DEEP_LENGTH",
		"接口尺寸" : "INTER_SIZE",
		"测量介质" : "MEDUIM_TYPE",
		"测量范围" : "MEARING_RANGE",
		"精度" : "MEASURE_ACC",				
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",				
		"测试日期" : "CHECK_TIME",
		"周期" : "CHECK_CYCLE",
		"备注信息" : "REMARK1"		
	},
	"气动切断阀" : {
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"介质" : "MEDUIM_TYPE",
		"法兰规格" : "FLA_SIZE",
		"作用方式" : "ACTION_MODLE",
		"有无手轮" : "HAVE_NOT",
		"执行机构型号" : "ACTUAL_MODEL",	
		"电磁阀型号" : "VAVLE_TYPE",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"备注信息" : "REMARK1"		
	},
	"气动调节阀" : {
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"介质	" : "MEDUIM_TYPE",
		"行程" : "	MEARING_RANGE",
		"CV值" : "CV",
		"法兰规格" : "FLA_SIZE",
		"作用方式" : "ACTION_MODLE",
		"有无手轮" : "HAVE_NOT",
		"执行机构型号" : "ACTUAL_MODEL",
		"气源Mpa" : "GAS_SOURCE",
		"定位器" : "POSITIONER",
		"电磁阀" : "VAVLE_TYPE",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"备注" : "REMARK1"
	},
	"液位计(含远程)" : {
		"规格型号" : "EQU_MODEL",
		"中心距离" : "DEEP_LENGTH",
		"安装地点" : "EQU_INSTALL_POSITION",
		"测量介质" : "MEDUIM_TYPE",
		"过程连接尺寸" : "PROCE_LINK_TYPE",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"备注" : "REMARK1"					
	},
	"流量计" : {
		"规格型号" : "EQU_MODEL",				
		"安装地点" : "EQU_INSTALL_POSITION",
		"介质" : "MEDUIM_TYPE",
		"流量(max)" : "ACTUAL",
		"流量(正常)" : "FLUX",
		"精 度" : "MEASURE_ACC",
		"测量范围" : "MEARING_RANGE",			
		"过程安装方式" : "PROCE_LINK_TYPE",				
		"编号" : "SERIAL_NUM",
		"生产厂家" : "EQU_MANUFACTURER",
		"生产日期" : "EQU_PRODUC_DATE",
		"备注" : "REMARK1"	
	},		

	"节流装置" : {
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"测量介质" : "MEDUIM_TYPE",
		"量程" : "MEARING_RANGE",
		"压力MPa" : "PRESSURE_RANGE",
		"温度" : "EQU_WORK_TEMP",
		"法兰规格" : "FLA_SIZE",
		"生产厂家" : "EQU_MANUFACTURER",
		"备注" : "REMARK1"
	},
	"在线分析仪" : {			
		"规格型号" : "EQU_MODEL",
		"安装地点" : "EQU_INSTALL_POSITION",
		"测量介质" : "MEDUIM_TYPE",
		"量程" : "MEARING_RANGE",
		"精 度" : "MEASURE_ACC",
		"测量原理" : "MEASURE_PRIN",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"备注" : "REMARK1"
	},

//			"震动温度探头" : {
//				"" : "",
//			},
	"DCS SIS系统" : {
		"控制器电源" : "ELEC_MODEL",
		"控制器MD" : "EQU_COMMISSION_DATE",
		"控制器MQ" : "MEDUIM_TYPE",
		"AI16" : "EQU_WORK_TEMP",
		"AI18-R" : "EQU_LASTPERIODIC_DATE",
		"AI08-R" : "EQU_PERIODIC_CYCLE",
		"DI32" : "EQU_PERIODIC_WARNDAYS",
		"DO32" : "MEARING_RANGE",
		"串口卡(个)" : "PRESSURE_RANGE",
		"串口卡(对)" : "MANAGE_TYPE",
		"SIS卡(对)" : "SERIAL_NUM",
		"24VDC/20A(对)" : "CHECK_CYCLE",
		"24VDC/40A(对)" : "CHECK_TIME",
		"12VDC/15A(对)" : "NEXT_CHECK_TIME",
		"中继器" : "EXPERY_TIME",
		"AI8" : "INTER_SIZE",
		"AI浪涌" : "MEASURE_ACC",
		"DI浪涌" : "DEEP_LENGTH",
		"继电器" : "ORDER_NUM",
		"备注" : "REMARK1"
	},
	"FGS系统" : {
		"控制器8851" : "MEDUIM_TYPE",
		"模拟量卡件8810" : "EQU_WORK_TEMP",
		"数字量卡件8811" : "EQU_LASTPERIODIC_DATE",
		"电源881312VDC/5A" : "EQU_PERIODIC_CYCLE",
		"电源RM240-24VDC/40A" : "EQU_PERIODIC_WARNDAYS",
		"电源RM120-24VDC/20A" : "MEARING_RANGE",
		"备注" : "REMARK1"
	},
	"固定式报警仪" : {
		"器具类别" : "MANAGE_TYPE",
		"规格型号" : "EQU_MODEL",
		"安装使用地点" : "EQU_INSTALL_POSITION",
		"用途" : "ACTUAL",
		"安装方式" : "ACTION_MODLE",
		"精 度" : "MEASURE_ACC",
		"测量范围" : "MEARING_RANGE",
		"供电" : "ELEC",
		"输出信号(mA)" : "CV",
		"报警值" : "ORDER_NUM",
		"生产厂家" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"有效期" : "NEXT_CHECK_TIME",
		"备注" : "REMARK1"
	},
//			"其它" : {
//				"" : "",
//			}
	
	
//机械大类
	"C类设备" : {
		"规格型号(φ×δ×h)":"EQU_MODEL",	
		"投用年月 ":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"介质":"MEDUIM_TYPE",	
		"容积(m3)":"MEARING_RANGE",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"腐蚀裕度(mm)":"MEASURE_ACC",	
		"铭牌位号":"ACTION_MODLE",	
		"塔盘层数":"COUNT",	
		"重量(Kg)":"WEIGHT",	
		"主体材质":"MATERIAL",	
		"设计条件温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"D类设备" : {
		"规格型号(φ×δ×h)":"EQU_MODEL",	
		"投用年月 ":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"介质":"MEDUIM_TYPE",	
		"容积(m3)":"MEARING_RANGE",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"腐蚀裕度(mm)":"MEASURE_ACC",	
		"铭牌位号":"ACTION_MODLE",	
		"重量(Kg)":"WEIGHT",	
		"主体材质":"MATERIAL",	
		"设计条件温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"E类设备" : {
		"换热面积(m2)":"MEARING_RANGE",
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"重量(Kg)":"WEIGHT",	
		"设计条件管程压力(MPa)":"DESIGN_SHELL_PRES",	
		"设计条件管程温度(℃)":"DESIGN_SHELL_TEMP",	
		"设计条件壳程温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件壳程压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件管程压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件管程进口温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"操作条件管程出口温度(℃)":"OPTION_SHELL_OUT_TEMP",	
		"操作条件管程介质":"OPTION_SHELL_MEDUIM",	
		"操作条件进口温度(℃)":"OPTION_TUBE_IN_TEMP",	
		"操作条件管程出口温度(℃)":"OPTION_TUBE_OUT_TEMP",	
		"操作条件管程介质":"OPTION_TUBE_MEDUIM",	
		"主体材质壳体":"SHELL_MATERIAL",	
		"主体材质列管":"TUBE_MATERIAL",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"F类设备" : {
		"安装位置":"EQU_INSTALL_POSITION",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"介质":"MEDUIM_TYPE",	
		"容积(m3)":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"腐蚀裕度(mm)":"MEASURE_ACC",
		"铭牌位号":"ACTION_MODLE",	
		"重量(Kg)":"WEIGHT",
		"主体材质":"MATERIAL",	
		"设计条件温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"H类设备" : {
		"规格型号(φ×δ×h)":"EQU_MODEL",	
		"投用年月 ":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"介质":"MEDUIM_TYPE",	
		"容积(m3)":"MEARING_RANGE",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"腐蚀裕度(mm)":"MEASURE_ACC",	
		"铭牌位号":"ACTION_MODLE",	
		"重量(Kg)":"WEIGHT",	
		"主体材质":"MATERIAL",	
		"设计条件温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"R类设备" : {
		"规格型号(φ×δ×h)":"EQU_MODEL",	
		"投用年月 ":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"容积(m3)":"MEARING_RANGE",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"腐蚀裕度(mm)":"MEASURE_ACC",	
		"重量(Kg)":"WEIGHT",	
		"主体材质":"MATERIAL",	
		"设计条件温度(℃)":"DESIGN_TUBE_TEMP",	
		"设计条件压力(MPa)":"DESIGN_TUBE_PRES",	
		"操作条件压力(MPa)":"OPTION_SHELL_PRESS",	
		"操作条件温度(℃)":"OPTION_SHELL_IN_TEMP",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"P类设备" : {
		"安装位置" : "EQU_INSTALL_POSITION",
		"类别" : "MANAGE_TYPE",
		"规格型号" : "EQU_MODEL",
		"重量" : "WEIGHT",
		"扬程" : "FLUX",
		"排量" : "COUNT",
		"电压" : "ELECTRIC_PRES",
		"功率" : "POWER_RATE",
		"转速" : "SPEED_RAT",
		"介质" : "MEDUIM_TYPE",
		"泵壳" : "CAPCITY",
		"叶轮" : "BEFORE_BEARING1",
		"主轴" : "BEFORE_BEARING2",
		"制造单位" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"投用年月" : "EQU_COMMISSION_DATE",
		"备注" : "REMARK1"
	},							
	"K类设备" : {
		"安装位置" : "EQU_INSTALL_POSITION",
		"类别" : "MANAGE_TYPE",
		"规格型号" : "EQU_MODEL",
		"重量" : "WEIGHT",
		"出口风压" : "WIND_PRESSURE",
		"排量" : "COUNT",
		"性能转速" : "SPEED_RAT",
		"电压" : "ELECTRIC_PRES",
		"功率" : "POWER_RATE",
		"电机转速" : "SPINDLE_SPEED",
		"介质" : "MEDUIM_TYPE",
		"制造单位" : "EQU_MANUFACTURER",
		"出厂编号" : "SERIAL_NUM",
		"投用年月" : "EQU_COMMISSION_DATE",
		"备注" : "REMARK1"
	},
	"机修类":{
		"规格型号":"EQU_MODEL",	
		"投用年月":"EQU_COMMISSION_DATE",	
		"制造单位":"EQU_MANUFACTURER",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"数量":"COUNT",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"车辆类":{
		"规格型号":"EQU_MODEL",	
		"投用年月":"EQU_COMMISSION_DATE",	
		"制造单位":"EQU_MANUFACTURER",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"能力":"CAPCITY",	
		"发动机号":"ENGINE_NUMBER",	
		"车牌号":"LICENSE_NUMBER",	
		"底盘号":"CHASSIS_NUMBER",	
		"能耗(L)":"ENERGY_CONSUMPTION",	
		"耗能种类":"ENERGY_CONSUMPTION_CAT",	
		"备注":"REMARK1",	
		"车辆名称":"EQU_NAME"
	},
	"其他":{
		"投用年月":"EQU_COMMISSION_DATE",	
		"制造单位":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"数量":"COUNT",	
		"主要技术参数":"HEIGHT_ELECTRIC_TENSION",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"A类分析仪器":{
		"规格型号":"EQU_MODEL",	
		"安 装 地 点":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"位  号":"EQU_POSITION_NUM",	
		"介质":"MEDUIM_TYPE",	
		"测量范围":"MEARING_RANGE",	
		"计量器具管理类别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"检定周期(月)":"CHECK_CYCLE",	
		"检定日期":"CHECK_TIME",	
		"下次检定日期":"NEXT_CHECK_TIME",	
		"准确度等级":"MEASURE_ACC",	
		"检定单位":"ACTION_MODLE",	
		"备注":"REMARK1",	
		"器具名称":"EQU_NAME"
	},
	"EPS电源系统":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"工作性质":"MEDUIM_TYPE",	
		"蓄电池型号":"EQU_WORK_TEMP",	
		"蓄电池品牌":"EQU_LASTPERIODIC_DATE",	
		"蓄电池容量":"EQU_PERIODIC_CYCLE",	
		"防护等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"蓄电池数量":"COUNT",	
		"功率":"POWER_RATE",	
		"输入电压":"ELECTRIC_PRES",	
		"输出电压":"ELECTRIC_TENSION",	
		"频率":"FREQUENCY",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	},
	"UPS电源系统":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"工作性质":"MEDUIM_TYPE",	
		"蓄电池型号":"EQU_WORK_TEMP",	
		"蓄电池品牌":"EQU_LASTPERIODIC_DATE",	
		"蓄电池容量":"EQU_PERIODIC_CYCLE",	
		"防护等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"蓄电池数量":"COUNT",	
		"输入电压":"ELECTRIC_PRES",	
		"输出电压":"ELECTRIC_TENSION",	
		"频率":"FREQUENCY",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"低压配电柜":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"出厂编号":"SERIAL_NUM",	
		"额定电压":"ELECTRIC_PRES",	
		"额定电流":"ELECTRIC_TENSION",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"电动机":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"工作性质":"MEDUIM_TYPE",	
		"蓄电池型号":"EQU_WORK_TEMP",	
		"蓄电池品牌":"EQU_LASTPERIODIC_DATE",	
		"蓄电池容量":"EQU_PERIODIC_CYCLE",	
		"防护等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"蓄电池数量":"COUNT",	
		"输入电压":"ELECTRIC_PRES",	
		"输出电压":"ELECTRIC_TENSION",	
		"频率":"FREQUENCY",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"干式变压器":{
		"规格型号":"EQU_MODEL",	
		"出厂时间":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"容量":"EQU_PERIODIC_CYCLE",	
		"绝缘等级":"MEARING_RANGE",	
		"接线组别":"MANAGE_TYPE",	
		"出厂编号":"SERIAL_NUM",	
		"相数":"COUNT",	
		"高压侧电压":"ELECTRIC_PRES",	
		"高压侧电流":"ELECTRIC_TENSION",	
		"低压侧电压":"FREQUENCY",	
		"低压侧电流":"BRAND",	
		"重量":"WEIGHT",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"高压配电柜":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"防护等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"对应设备":"ACTION_MODLE",	
		"额定短时工频耐受电压":"ELECTRIC_PRES",	
		"额定雷电冲击耐受电压":"ELECTRIC_TENSION",	
		"额定短时耐受电流":"FREQUENCY",	
		"额定峰值耐受电流":"BRAND",	
		"相数":"WEIGHT",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"	
	},
	"现场配电箱":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"设备用途":"MEDUIM_TYPE",	
		"防爆区域等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"主要运行参数":"HEIGHT_ELECTRIC_TENSION",	
		"防爆合格证号":"WEIGHT",	
		"防爆标志":"MATERIAL",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME",	
	},
	"直流电源系统":{
		"规格型号":"EQU_MODEL",	
		"生产日期":"EQU_PRODUC_DATE",	
		"投运日期":"EQU_COMMISSION_DATE",	
		"安装位置":"EQU_INSTALL_POSITION",	
		"生产厂家":"EQU_MANUFACTURER",	
		"设备位号":"EQU_POSITION_NUM",	
		"蓄电池型号":"EQU_WORK_TEMP",	
		"品牌":"EQU_LASTPERIODIC_DATE",	
		"蓄电池容量":"EQU_PERIODIC_CYCLE",	
		"防护等级":"MEARING_RANGE",	
		"出厂编号":"SERIAL_NUM",	
		"蓄电池数量":"COUNT",	
		"额定交流电压":"ELECTRIC_PRES",	
		"额定电流":"ELECTRIC_TENSION",	
		"频率":"FREQUENCY",	
		"额定直流电压":"BRAND",	
		"备注":"REMARK1",	
		"设备名称":"EQU_NAME"
	}
};